// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartPotsWeb.Models;

#nullable disable

namespace SmartPotsWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403070325_ApplyTelemetryOptimization")]
    partial class ApplyTelemetryOptimization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartPotsWeb.Data.CurrentHubState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CurrentHum")
                        .HasColumnType("real");

                    b.Property<int>("CurrentLux")
                        .HasColumnType("integer");

                    b.Property<float>("CurrentTemp")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("PreviousHum")
                        .HasColumnType("real");

                    b.Property<int>("PreviousLux")
                        .HasColumnType("integer");

                    b.Property<float>("PreviousTemp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CurrentHubStates");
                });

            modelBuilder.Entity("SmartPotsWeb.Data.HubTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("DailyLuxHours")
                        .HasColumnType("real");

                    b.Property<float>("Hum")
                        .HasColumnType("real");

                    b.Property<bool>("HumidifierOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("LightOn")
                        .HasColumnType("boolean");

                    b.Property<int>("Lux")
                        .HasColumnType("integer");

                    b.Property<int>("MinuteOfDay")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<float>("Temp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HubTelemetries");
                });

            modelBuilder.Entity("SmartPotsWeb.Data.PlantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Autumn", "SmartPotsWeb.Data.PlantProfile.Autumn#SeasonalSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AirHumidity")
                                .HasColumnType("integer");

                            b1.Property<int>("LightLux")
                                .HasColumnType("integer");

                            b1.Property<int>("SoilMoisture")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Spring", "SmartPotsWeb.Data.PlantProfile.Spring#SeasonalSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AirHumidity")
                                .HasColumnType("integer");

                            b1.Property<int>("LightLux")
                                .HasColumnType("integer");

                            b1.Property<int>("SoilMoisture")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Summer", "SmartPotsWeb.Data.PlantProfile.Summer#SeasonalSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AirHumidity")
                                .HasColumnType("integer");

                            b1.Property<int>("LightLux")
                                .HasColumnType("integer");

                            b1.Property<int>("SoilMoisture")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Winter", "SmartPotsWeb.Data.PlantProfile.Winter#SeasonalSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("AirHumidity")
                                .HasColumnType("integer");

                            b1.Property<int>("LightLux")
                                .HasColumnType("integer");

                            b1.Property<int>("SoilMoisture")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("SmartPotsWeb.Data.Pot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HardwareId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("PlantProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PlantingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlantProfileId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("SmartPotsWeb.Data.PotTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HardwareId")
                        .HasColumnType("integer");

                    b.Property<int>("HubTelemetryId")
                        .HasColumnType("integer");

                    b.Property<int>("Moisture")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlantProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<int>("TargetAir")
                        .HasColumnType("integer");

                    b.Property<int>("TargetLux")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HubTelemetryId");

                    b.HasIndex("PlantProfileId");

                    b.ToTable("PotTelemetries");
                });

            modelBuilder.Entity("SmartPotsWeb.Data.Pot", b =>
                {
                    b.HasOne("SmartPotsWeb.Data.PlantProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("PlantProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SmartPotsWeb.Data.PotTelemetry", b =>
                {
                    b.HasOne("SmartPotsWeb.Data.HubTelemetry", "Hub")
                        .WithMany("Pots")
                        .HasForeignKey("HubTelemetryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPotsWeb.Data.PlantProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("PlantProfileId");

                    b.Navigation("Hub");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SmartPotsWeb.Data.HubTelemetry", b =>
                {
                    b.Navigation("Pots");
                });
#pragma warning restore 612, 618
        }
    }
}
