// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartPotsWeb.Models;

#nullable disable

namespace SmartPotsWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartPotsWeb.Models.HubTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Hum")
                        .HasColumnType("real");

                    b.Property<bool>("LightOn")
                        .HasColumnType("boolean");

                    b.Property<int>("Lux")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Temp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HubTelemetries");
                });

            modelBuilder.Entity("SmartPotsWeb.Models.PlantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeMonths")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUri")
                        .HasColumnType("text");

                    b.Property<int>("PhysicalPort")
                        .HasColumnType("integer");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("SmartPotsWeb.Models.PotTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HubTelemetryId")
                        .HasColumnType("integer");

                    b.Property<int>("Moisture")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlantProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HubTelemetryId");

                    b.HasIndex("PlantProfileId");

                    b.ToTable("PotTelemetries");
                });

            modelBuilder.Entity("SmartPotsWeb.Models.PlantProfile", b =>
                {
                    b.OwnsOne("SmartPotsWeb.Models.SeasonSettings", "TargetAirHumidity", b1 =>
                        {
                            b1.Property<Guid>("PlantProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Autumn")
                                .HasColumnType("integer");

                            b1.Property<int>("Spring")
                                .HasColumnType("integer");

                            b1.Property<int>("Summer")
                                .HasColumnType("integer");

                            b1.Property<int>("Winter")
                                .HasColumnType("integer");

                            b1.HasKey("PlantProfileId");

                            b1.ToTable("PlantProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PlantProfileId");
                        });

                    b.OwnsOne("SmartPotsWeb.Models.SeasonSettings", "TargetLux", b1 =>
                        {
                            b1.Property<Guid>("PlantProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Autumn")
                                .HasColumnType("integer");

                            b1.Property<int>("Spring")
                                .HasColumnType("integer");

                            b1.Property<int>("Summer")
                                .HasColumnType("integer");

                            b1.Property<int>("Winter")
                                .HasColumnType("integer");

                            b1.HasKey("PlantProfileId");

                            b1.ToTable("PlantProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PlantProfileId");
                        });

                    b.OwnsOne("SmartPotsWeb.Models.SeasonSettings", "TargetSoilMoisture", b1 =>
                        {
                            b1.Property<Guid>("PlantProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Autumn")
                                .HasColumnType("integer");

                            b1.Property<int>("Spring")
                                .HasColumnType("integer");

                            b1.Property<int>("Summer")
                                .HasColumnType("integer");

                            b1.Property<int>("Winter")
                                .HasColumnType("integer");

                            b1.HasKey("PlantProfileId");

                            b1.ToTable("PlantProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PlantProfileId");
                        });

                    b.Navigation("TargetAirHumidity")
                        .IsRequired();

                    b.Navigation("TargetLux")
                        .IsRequired();

                    b.Navigation("TargetSoilMoisture")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartPotsWeb.Models.PotTelemetry", b =>
                {
                    b.HasOne("SmartPotsWeb.Models.HubTelemetry", "Hub")
                        .WithMany("Pots")
                        .HasForeignKey("HubTelemetryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPotsWeb.Models.PlantProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("PlantProfileId");

                    b.Navigation("Hub");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SmartPotsWeb.Models.HubTelemetry", b =>
                {
                    b.Navigation("Pots");
                });
#pragma warning restore 612, 618
        }
    }
}
